source/web-service/flaskapp/routes/activity.py
import math

from flask import Blueprint, current_app, abort, request, redirect, jsonify, url_for
from sqlalchemy.orm import joinedload
from sqlalchemy.sql.functions import coalesce, max
from sqlalchemy import func

# date parsing
import dateparser

from flaskapp.models import db
from flaskapp.models.activity import Activity
from flaskapp.models.record import Record
from flaskapp.utilities import format_datetime
from flaskapp.errors import (
    construct_error_response,
    status_record_not_found,
    status_pagenum_not_integer,
    status_page_not_found,
)


# Create a new "activity" route blueprint
activity = Blueprint("activity", __name__)


@activity.route("/activity-stream/skip-to-datetime")
@activity.route("/activity-stream/skip-to-datetime/<string:target_datetime>")
def redirect_to_page_using_datetime(target_datetime=None):
    if "datetime" in request.args:
        target_datetime = request.args["datetime"]

    if not target_datetime:
        # response - bad request
        return (
            jsonify({"errors": [{"error": "Datetime was not specified."}]}),
            400,
        )

    try:
        datetime_obj = dateparser.parse(
            target_datetime,
            settings={"RETURN_AS_TIMEZONE_AWARE": True},
        )
        if datetime_obj is None:
            # response - bad request, unparsable date
            return (
                jsonify({"errors": [{"error": "Datetime was not understood"}]}),
                400,
            )
    except (ValueError, TypeError) as e:
        current_app.logger.debug(
            f"There was an error decoding the date provided: '{target_datetime}' - {e}"
        )
        return (
            jsonify({"errors": [{"error": "Datetime was not understood"}]}),
            400,
        )

    # Try to find the closest Activity id to suggested date
    # The datetime is not indexed at the moment but could be eventually. This
    # initial query will be slow until then!
    if closest_log := (
        Activity.query.filter(Activity.datetime_created >= datetime_obj)
        .order_by(Activity.id)
        .first()
    ):
        limit = current_app.config["ITEMS_PER_PAGE"]
        page = (closest_log.id // limit) + 1
        current_app.logger.debug(
            f"Redirecting to page {page} for Activity.id {closest_log.id} due to "
            f"datetime {target_datetime} - parsed as {datetime_obj}"
        )
        return redirect(url_for("activity.activity_stream_page", pagenum=page))
    else:
        return (
            jsonify(
                {
                    "errors": [
                        {
                            "error": f"No Activity entries found newer than specified date: '{target_datetime}'."
                        }
                    ]
                }
            ),
            404,
        )


@activity.route("/activity-stream")
@activity.route("/activity-stream/")
def activity_stream_collection():
    """Generate the root OrderedCollection for the stream

    TODO: This does not currently filter against namespaces for the count. Should it?

    Returns:
        Response: A JSON-encoded OrderedCollection
    """

    count = db.session.query(func.count(Activity.id)).scalar()
    total_pages = str(compute_total_pages())

    data = {
        "@context": "https://www.w3.org/ns/activitystreams",
        "summary": current_app.config["AS_DESC"],
        "type": "OrderedCollection",
        "id": generate_url(),
        "totalItems": count,
    }

    if count:
        data["first"] = {
            "id": generate_url(sub=["page", "1"]),
            "type": "OrderedCollectionPage",
        }
        data["last"] = {
            "id": generate_url(sub=["page", total_pages]),
            "type": "OrderedCollectionPage",
        }

    return current_app.make_response(data)


# Abort if 'pagenum' is not integer
@activity.route("/activity-stream/page/<string:pagenum>")
def activity_stream_wrong_page_format(pagenum):
    response = construct_error_response(status_pagenum_not_integer)
    return abort(response)


@activity.route("/activity-stream/page/<int:pagenum>")
def activity_stream_page(pagenum):
    """Generate an OrderedCollectionPage of Activity Stream items.

    Args:
        pagenum (Integer): The page to generate

    Returns:
        TYPE: Response: a JSON-encoded OrderedCollectionPage
    """

    limit = current_app.config["ITEMS_PER_PAGE"]
    offset = (pagenum - 1) * limit
    total_pages = compute_total_pages()

    if pagenum == 0 or pagenum > total_pages:
        response = construct_error_response(status_page_not_found)
        return abort(response)

    data = {
        "@context": "https://www.w3.org/ns/activitystreams",
        "type": "OrderedCollectionPage",
        "id": generate_url(sub=["page", str(pagenum)]),
        "partOf": {"id": generate_url(), "type": "OrderedCollection"},
    }

    if pagenum < total_pages:
        data["next"] = {
            "id": generate_url(sub=["page", str(pagenum + 1)]),
            "type": "OrderedCollectionPage",
        }

    if pagenum > 1:
        data["prev"] = {
            "id": generate_url(sub=["page", str(pagenum - 1)]),
            "type": "OrderedCollectionPage",
        }

    if activities := (
        Activity.query.options(
            joinedload(Activity.record, innerjoin=True).defer(Record.data)
        )
        .filter(Activity.id > offset, Activity.id <= offset + limit)
        .order_by("id")
    ):

        items = [generate_item(a) for a in activities]
        data["orderedItems"] = items
    else:
        data["orderedItems"] = []

    return current_app.make_response(data)


@activity.route("/activity-stream/<string:uuid>")
def activity_stream_item(uuid):
    """Generate an ActivityStreams Create Response

    Args:
        uuid (String): The ID of the ActivityStream Create entity

    Returns:
        Response:  a JSON-encoded Create entity
    """

    activity = (
        Activity.query.options(joinedload(Activity.record, innerjoin=True))
        .filter(Activity.uuid == uuid)
        .one_or_none()
    )

    if not activity:
        response = construct_error_response(status_record_not_found)
        return abort(response)

    data = generate_item(activity)

    return current_app.make_response(data)


def compute_total_pages():
    limit = current_app.config["ITEMS_PER_PAGE"]
    # Quick count
    last = db.session.query(coalesce(max(Activity.id), 0).label("num")).one()
    return math.ceil(last.num / limit)


def generate_url(sub=[], base=False):
    """Create a URL string from relevant fragments

    Args:
        sub (list, optional): A list of additional URL parts
        base (bool, optional): Should the "activity-stream" part be added?

    Returns:
        String: The generated URL string
    """
    base_url = current_app.config["BASE_URL"]
    namespace = current_app.config["NAMESPACE"]

    if base:
        as_prefix = None
    else:
        as_prefix = "activity-stream"

    parts = [base_url, namespace, as_prefix, "/".join(sub)]
    parts = [item for item in parts if item]
    return "/".join(parts)


def generate_item(activity):
    """Generate the ActivityStream Create record

    Args:
        activity (Activity): The Activity record to generate

    Returns:
        Dict: The generated data structure
    """
    return {
        "id": generate_url(sub=[str(activity.uuid)]),
        "type": activity.event,
        "created": format_datetime(activity.datetime_created),
        "endTime": format_datetime(activity.datetime_created),
        "object": {
            "id": generate_url(base=True, sub=[str(activity.record.entity_id)]),
            "type": activity.record.entity_type,
        },
    }

source/web-service/flaskapp/routes/sparql.py
import time

from flask import (
    Blueprint,
    current_app,
    request,
    abort,
    Response,
    make_response,
)

from flaskapp.errors import (
    status_nt,
    construct_error_response,
)

from flaskapp.utilities import execute_sparql_query_post, execute_sparql_query

# Create a new "sparql" route blueprint
sparql = Blueprint("sparql", __name__)


# ### ROUTES ###
@sparql.route("/sparql", methods=["GET", "POST"])
def query_entrypoint():
    if current_app.config["PROCESS_RDF"] is not True:
        response = construct_error_response(
            status_nt(
                501,
                "Not Implemented",
                "Application is not enabled for SPARQL operations",
            )
        )
        return abort(response)

    if "update" in request.args or request.form.get("update") is not None:
        response = construct_error_response(
            status_nt(400, "Bad Request", "SPARQL update is not permitted")
        )
        return abort(response)

    query: str = None

    if "query" in request.args:
        query = request.args["query"]
    elif "query" in request.form:
        query = request.form["query"]

    current_app.logger.debug(str(request.form))
    current_app.logger.debug(str(request.data))
    current_app.logger.debug(f"query: {query}")

    if (
        query is None
        and request.headers.get("Content-Type") == "application/sparql-query"
    ):
        query = request.data

    if query is None:
        response = construct_error_response(
            status_nt(400, "Bad Request", "No query parameter included")
        )
        return abort(response)

    accept_header: str = None

    if "Accept" in request.args:
        accept_header = request.args["Accept"]
    else:
        accept_header = request.form.get("Accept")

    if accept_header is None:
        accept_header = request.headers.get("Accept")

    query_endpoint = current_app.config["SPARQL_QUERY_ENDPOINT"]

    if request.method == "POST":
        st = time.perf_counter()
        res = execute_sparql_query_post(
            # The request.form key-value pairs are combined with the query key-value
            # pair to ensure the query string is always sent to execute_sparql_query_post()
            # whether provided via request.args, request.form, or request.data:
            dict(request.form, query=query),
            accept_header,
            query_endpoint,
        )
        current_app.logger.info(
            f"Remote SPARQL POST query executed in {time.perf_counter() - st:.2f}s"
        )

        if isinstance(res, status_nt):
            response = construct_error_response(res)
            return abort(response)
        else:
            excluded_headers = [
                "content-encoding",
                "content-length",
                "transfer-encoding",
                "connection",
            ]

            headers = [
                (name, value)
                for (name, value) in res.headers.items()
                if name.lower() not in excluded_headers
            ]

            return make_response(res.content, res.status_code, headers)
    else:
        st = time.perf_counter()
        res = execute_sparql_query(query, accept_header, query_endpoint)

        current_app.logger.debug(
            f"Remote SPARQL GET query executed in {time.perf_counter() - st:.2f}s"
        )
    if isinstance(res, status_nt):
        response = construct_error_response(res)
        return abort(response)
    else:
        return Response(res, direct_passthrough=True, content_type=accept_header)

source/web-service/flaskapp/routes/yasgui.py
from flask import Blueprint, current_app, abort
from flaskapp.errors import status_nt, construct_error_response

# Create a new "yasgui" route blueprint
yasgui = Blueprint("yasgui", __name__)


# ### ROUTES ###
@yasgui.route("/sparql-ui", methods=["GET"])
def get_yasgui():
    if current_app.config["PROCESS_RDF"] is not True:
        response = construct_error_response(
            status_nt(
                501,
                "Not Implemented",
                "Application is not enabled for SPARQL operations",
            )
        )
        return abort(response)

    endpoint = (
        current_app.config["BASE_URL"]
        + "/"
        + current_app.config["NAMESPACE"]
        + "/sparql"
    )
    yasgui_page = create_yasgui_html(endpoint)
    return yasgui_page


def create_yasgui_html(endpoint):
    head = (
        "<head>"
        "<link href='https://unpkg.com/@triply/yasgui/build/yasgui.min.css' rel='stylesheet' type='text/css' />"
        "<script src='https://unpkg.com/@triply/yasgui/build/yasgui.min.js'></script>"
        "</head>"
    )
    body = (
        "<body>"
        "<div id='yasgui'></div>"
        "<script>"
        "const yasgui = new Yasgui(document.getElementById('yasgui'), "
        "{requestConfig: { endpoint: "
        f"'{endpoint}'"
        "}, copyEndpointOnNewTab: false}); "
        "</script>"
        "<style> .yasgui .autocompleteWrapper { visibility: hidden } .yasr .tableControls .tableFilter { margin-right: 10px; height: auto !important; } </style>"
        "</body>"
    )

    return head + body

source/web-service/flaskapp/templates/home_page.html
{# templates/home_page.html #}

<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <link rel="preconnect" href="https://fonts.googleapis.com" />
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
    <link href="https://fonts.googleapis.com/css2?family=Roboto&display=swap" rel="stylesheet" />
    <link
      href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@24,600,0,200"
      rel="stylesheet"
    />
    <link href="https://unpkg.com/material-design-lite@1.3.0/material.min.css" rel="stylesheet" />
  </head>
  <style>
    *,
    *::before,
    *::after {
      -webkit-box-sizing: border-box;
      box-sizing: border-box;
    }

    html {
      background-color: rgb(248, 240, 250);
    }

    body,
    p {
      font-size: 16px;
      font-weight: 400;
      line-height: 24px; /* 150% */
      letter-spacing: 0.5px;
      font-family: "Roboto", sans-serif;
    }

    h1 {
      font-size: 52px;
      line-height: 64px;
      margin: 0;
    }

    h2 {
      font-size: 32px;
      line-height: 40px;
      margin: 0;
      word-wrap: break-word;
      word-break: break-word;
    }

    h3 {
      font-size: 22px;
      line-height: 28px;
      margin: 0;
    }

    a {
      color: #6750a4;
      font-weight: 400;
    }

    .container {
      margin-top: 96px;
      margin-right: auto;
      margin-left: auto;
      padding-right: 15px;
      padding-left: 15px;
      width: 100%;
      max-width: 1140px;
    }

    .hero {
      display: flex;
      justify-content: space-between;
      margin-top: 32px;
    }

    .hero_left-column {
      width: 50%;
    }

    .hero_aslinks {
      margin-top: 24px;
    }

    .hero_right-column {
      border: 1px solid #cac4d0;
      border-radius: 12px;
      padding: 24px;
      width: 42%;
    }

    .hero_stats {
      display: flex;
      column-gap: 32px;
      margin-top: 32px;
    }

    .hero_timestamp {
      color: #49454f;
      margin-top: 12px;
    }

    .hero_badges {
      display: flex;
      margin-top: 12px;
      column-gap: 23px;
    }

    .hero_badge {
      display: flex;
      column-gap: 5px;
      align-items: flex-start;
    }

    .hero_badge-indicator {
      background-color: #6750a4;
      border-radius: 100%;
      height: 24px;
      width: 24px;
    }

    .hero_badge-indicator--disabled {
      opacity: .3;
    }

    .hero_badge-indicator span {
      color: #ffffff;
    }

    .hero_sparql-links {
      margin-top: 12px;
      display: flex;
      flex-direction: column;
      row-gap: 10px;
    }

    .hero_sparql-links div {
      display: flex;
      align-items: flex-start;
      column-gap: 4px;
      color: #6750a4;
    }

    .entities {
      margin-top: 60px;
    }

    .entity_row {
      display: flex;
      margin-top: 32px;
      background-color: #eeeaf4;
      border-radius: 12px;
    }

    .entity_left-column,
    .entity_right-column {
      width: 50%;
      padding: 24px;
    }

    .entity_left-column {
      background-color: #ffffff;
      border-radius: 12px;
    }

    .entity_records,
    .entity_changes {
      margin-top: 24px;
      display: flex;
      align-items: center;
      column-gap: 4px;
    }

    .entity_records span,
    .entity_changes span {
      color: #6750a4;
    }

    .entity_changes {
      margin-top: 12px;
    }

    .entity_timestamp {
      margin-top: 24px;
      margin-bottom: 4px;
    }

    .entity_right-column {
      margin-top: 64px;
    }

    .entity_recent-change {
      display: flex;
      column-gap: 4px;
      align-items: flex-start;
      color: #6750a4;
      margin-top: 32px;
      overflow-wrap: break-word;
      word-wrap: break-word;
      word-break: break-word;
    }

    .entity_links {
      margin-top: 32px;
      display: flex;
      flex-direction: column;
    }

    .documentation {
      width: 100%;
      margin-right: auto;
      margin-left: auto;
      padding-right: 15px;
      padding-left: 15px;
      background-color: #e7e0ec;
    }

    .documntation_container {
      padding-top: 64px;
      padding-bottom: 90px;
    }

    .documnetation_columns {
      display: flex;
      justify-content: space-between;
      margin-top: 64px;
    }

    .documnetation_column {
      display: flex;
      flex-direction: column;
      row-gap: 16px;
      width: 18%;
      margin-top: 0;
    }

    .documnetation_column h3 {
      border-bottom: 1px solid #cac4d0;
      margin-bottom: 35px;
      padding-bottom: 4px;
    }

    footer {
      padding-bottom: 96px;
    }

    footer hr {
      margin: 32px 0;
    }

    /* responsive styles */
    @media (max-width: 576px) {
      .container {
        max-width: 540px;
      }
    }
    @media (max-width: 768px) {
      .container {
        max-width: 720px;
      }

      .hero {
        flex-wrap: wrap;
      }

      .hero_left-column,
      .hero_right-column {
        width: 100%;
        margin-bottom: 32px;
      }

      .entity_row {
        flex-wrap: wrap;
      }

      .entity_left-column,
      .entity_right-column {
        width: 100%;
      }

      .documnetation_columns {
        flex-wrap: wrap;
      }

      .documnetation_column {
        width: 50%;
        margin-top: 60px;
      }
    }
    @media (max-width: 992px) {
      .container {
        max-width: 960px;
      }
    }
  </style>

  <body>
    <div class="container">
      <h1 class="title">{{ lod_name }}</h1>
      <div class="hero">
        <div class="hero_left-column">
          <div class="hero_description" style="padding-right: 45px">
            <p>
              The LOD Gateway is an RDF enabled, fast-cache for storing entity information as JSON documents. 
              The LOD Gateway provides API endpoints primarily for obtaining JSON entity documents and an
              Activity Stream to track changes in entity state. Optionally serve raw JSON from source systems or fully
              enable JSON-LD including RDF expansion and a SPARQL endpoint for querying RDF graph data.
            </p>
          </div>
          {% if num_records != "0" %}
          <div class="hero_aslinks">           
            <a href="{{ url_for('activity.activity_stream_collection') }}">View activity stream</a>
            <span>(</span>
            <a href="{{ url_for('activity.activity_stream_page', pagenum=1) }}">oldest</a>
            <span> | </span>
            <a href="{{ url_for('activity.activity_stream_page', pagenum=as_last_page) }}"> newest</a>
            <span>)</span>
          </div>
          {% endif %}
        </div>

        <div class="hero_right-column">
          <h3>Stats</h3>
          <div class="hero_stats">
            <h2>{{ num_records }} records</h2>
            <h2>{{ num_changes }} changes</h2>
          </div>
          <div class="hero_timestamp">Last change made: {{ last_change }}</div>
          <div class="hero_badges">
            <div class="hero_badge">
              <p>SPARQL</p>
              <div class="{{"hero_badge-indicator" if chk_sparql == "checked" else "hero_badge-indicator hero_badge-indicator--disabled"}}">
                {% if chk_sparql == "checked" %}
                <span class="material-symbols-outlined"> done </span>
                {% else %}
                <span class="material-symbols-outlined"> close </span>
                {% endif %}
              </div>
            </div>
            <div class="hero_badge">
              <p>Memento</p>
              <div class="{{"hero_badge-indicator" if chk_memento == "checked" else "hero_badge-indicator hero_badge-indicator--disabled"}}">
                {% if chk_memento == "checked" %}
                <span class="material-symbols-outlined"> done </span>
                {% else %}
                <span class="material-symbols-outlined"> close </span>
                {% endif %}
              </div>
            </div>
          </div>
          {% if chk_sparql == "checked" %}
          <hr />
          <div class="hero_sparql-links">
            <div>
              <a href="{{ url_for('sparql.query_entrypoint') }}">SPARQL API link </a>
              <span class="material-symbols-outlined"> arrow_outward </span>
            </div>
            <div>
              <a href="{{ url_for('yasgui.get_yasgui') }}">SPARQL GUI link </a>
              <span class="material-symbols-outlined"> arrow_outward </span>
            </div>
          </div>
          {% endif %}
        </div>
      </div>

      <div class="entities">
        <h2>Entities ({{ num_entities }})</h2>
        {% for entity in entities %}
        <div class="entity_row">
          <div class="entity_left-column">
            <h2>{{ entity.entity_name }}</h2>
            <div class="entity_records">
              <span class="material-symbols-outlined">article</span>
              <h3>{{ entity.num_records }} records</h3>
            </div>
            <div class="entity_changes">
              <span class="material-symbols-outlined"> update </span>
              <h3>{{ entity.num_changes}} changes</h3>
            </div>
            <p class="entity_timestamp">Last updated: {{ entity.last_updated }}</p>
            <div class="entity_aslinks">
              <a
                href="{{ url_for('activity_entity.activity_stream_entity_collection', entity_type=entity.entity_name.lower()) }}"
                >View activity stream</a
              >
              <span>(</span>
              <a
                href="{{ url_for('activity_entity.activity_stream_entity_page', entity_type=entity.entity_name.lower(), pagenum=1) }}"
                >oldest</a
              >
              <span>|</span>
              <a
                href="{{ url_for('activity_entity.activity_stream_entity_page', entity_type=entity.entity_name.lower(), pagenum=entity.as_last_page) }}"
                >newest</a
              >
              <span>)</span>
            </div>
          </div>
          <div class="entity_right-column">
            <h3>Most recently changed record</h3>
            <div class="entity_recent-change">
              <span class="material-symbols-outlined"> link </span>
              <a href="{{ entity.most_recent_rec_url }}">{{ entity.most_recent_rec_url }}</a>
            </div>
            <p class="entity_timestamp">Last updated: {{ entity.most_recent_date }}</p>
            <p>{{ entity.most_recent_num_changes}} {{"changes" if entity.most_recent_num_changes > 1 else "change"}}</p>
            <div class="entity_links">
              {% if chk_memento == "checked" %}
              <a href="{{ url_for('timegate.get_timemap', entity_id=entity.most_recent_rec) }}"
                >View change log in Memento</a
              >
              {% endif %}
              <div class="entity_aslinks">
                <a href="{{ entity.most_recent_as }}">View activity stream</a><span> (</span>
                <a href="{{ entity.most_recent_as }}/page/1"> oldest</a><span> | </span>
                <a href="{{ entity.most_recent_as }}/page/{{ entity.num_pages_most_recent_as }}">newest</a><span> )</span>
              </div>
              {% if chk_sparql == "checked" %}
              <a href="{{ entity.most_recent_sparql }}">Link to SPARQL query</a>
              {% endif %}
            </div>
          </div>
        </div>
        {% endfor %}
      </div>
    </div>

    {% if link_bank %}
    <div class="documentation">
      <div class="documntation_container container">
        <h2>Documentation & resources</h2>
        <div class="documnetation_columns">
          {% for group in link_bank.groups %}
          <div class="document_column">
            <h3>{{ group.name }}</h3>
            <br />
            {% for link in group.links %}
            <a href="{{ link.url }}">{{ link.name }}</a><br />
            {% endfor %}
          </div>
          {% endfor %}
        </div>
      </div>
    </div>
    {% endif %}

    <footer class="container">
      <p>© 2023 The J. Paul Getty Trust. All rights reserved.</p>
      {% if lod_version %}
        <hr />
        <p>Version {{ lod_version }}</p>
      {% endif %}
    </footer>
  </body>
</html>